### ISSUE TITLE
Rewriting content-types for URLs

### ISSUE THREAD

**Issue by dhui** [atmos/camo#58]
@atmos, how do you feel about rewriting the content-type for URLs that return image data but don't return the correct content-type.

Example URL:
http://www.schwab.com/public/file/Japanese-inflation-adjusted-wages-continue-to-fall/Japanese_inflation_adjusted_wages_continue_to_fall
You'll notice `‰PNG  IHDR` in the first few bytes of the HTTP response.

How do you feel about a dependency on the `mmmagic` library?
https://github.com/mscdex/mmmagic

If camo were to support detection of content-types, I think this feature should be off by default.

**Comment by rafBM** [comment]
May I ask why should Camo do any Content-Type whitelisting at all? Is there any security concern when rendering an `img` with some `src` returning bad content and / or Content-Type? I doubt any browser would execute scripts or the like when loaded via an `img`’s `src`… ?

**Comment by atmos** [comment]
Yes, previous testing showed that returning and rendering stuff like text/html and others allow for script executions, so it's a no go.

**Comment by rafBM** [comment]
Ok. I am asking because we are developing an app using Camo and started seeing valid `.png` images from the web returned with no `Content-Type`, or weirder, `Content-Type: application/json`. Granted, these aren’t good web citizens, but still we’d rather have Camo render those images properly instead of broken 404’s (browsers are totally fine at rendering `.png` images served with no `Content-Type`, or even `image/gif` or `application/json`, they don’t seem to care much about the header).

So Camo’s current solution is to look at the `Content-Type` header and return a 404 if it’s not whitelisted. It is protecting you against receiving responses with `Content-Type: text/html` or `text/javascript`, etc. It is *not* protecting you against my “evil” website serving HTML/JS content with a seemingly legit `Content-Type: image/png`, right? So when receiving a non-whitelisted `Content-Type` (or none), why not just overwrite the `Content-Type` header with a whitelisted one, like `image/png`? Unless I’m missing something, this wouldn’t be any less secure than the current behavior.

I saw https://github.com/atmos/camo/pull/59 but reading the bytes sounds like too much overhead to me, especially for a lightweight app that should just proxy things.

**Comment by atmos** [comment]
Yeah, unfortunately a lot of the web is broken. We didn't run in to a significant amount of misconfigured servers sending back incorrect content-types at GitHub to ever address it. You can sort of cut your losses and do things correctly, or go down a rabbit hole of never ending one-offs with misunderstood security ramifications. I chose to keep it simple. Think of it like a firewall, only let in the stuff you specifically accept.
