### ISSUE TITLE
Forward Referrer header or other repo info

### ISSUE THREAD

**Issue by defunctzombie** [atmos/camo#98]
It would be cool if the referrer header for the original request was sent along. This would be useful for github repo badge images because they could detect the source of the request (i.e. the repo and branch) from this header. Alternatively, maybe just sending that info along in a custom header would be easier. 

The idea is that a badge could be put on a readme with a simple url `http://badge.com/badge.svg` and from the headers figure out which repo requested the badge. This would be great for when people fork repos or otherwise make branches and you want the badge to refer to the correct fork or branch.

**Comment by rmm5t** [comment]
This has been covered before:

* https://github.com/atmos/camo/issues/43
* https://github.com/blog/1766-proxying-user-images

The current behavior is done to protect privacy and prevent leaking information to third parties.

**Comment by defunctzombie** [comment]
@rmm5t what browser info or privacy would be leaked by providing the repo and branch from public repos? I understand the need to proxy overall, but think that some information could be included that would be cool for the service to provide a better experience.

I have read up on some of the previous discussions but wanted to raise this as a potential solution (an alternative to just sending the referrer header) since maybe the thinking has changed.

Note that while the issue is titled with the referrer header, I include other ways to solve this that don't involve sending a referrer header.

**Comment by rmm5t** [comment]
@defunctzombie I'm just regurgitating information and decisions that github and @atmos have already made public. i.e. Just helping to triage. 

In general though, relying on the (misspelled) "referer" header for almost anything is generally a bad idea anyway. Many proxy servers filter it out anyway. Many privacy web plugins filter it out. 

I understand your proposal to add a new header, but if camo isn't guaranteed to receive the "referer" header in the first place (because proxies and privacy plugins), how does that help?

**Comment by defunctzombie** [comment]
@rmm5t fair enough, just didn't know where else to propose the feature to send along this data except this repo. Maybe not the best place but it was only place I thought to discuss it.

**Comment by atmos** [comment]
> Maybe not the best place but it was only place I thought to discuss it.

It totally is the right way place to ask questions.

> what browser info or privacy would be leaked by providing the repo and branch from public repos?

There's a couple of things, mainly like what @rmm5t [mentioned](https://github.com/atmos/camo/issues/98#issuecomment-179973251) above.  There's definitely something to be gained by forwarding the referer, but it's not forwarded by design.

I also don't work at GitHub anymore so introducing the changes on this repo would likely never make it to github.com.

**Comment by j-manu** [comment]
We are using Camo to proxy images and some of the upstream providers whitelist the proxy using referer header than user agent. Currently we have patched camo but it will be nice to have it as an option.
